[platformio]
default_envs = esp01_1m

[default_envs]
build_flags = 
  -ffunction-sections 
  -Wl,--gc-sections
  -Wl,-Map=output.map
  -fverbose-asm
  -g
monitor_speed = 9600
monitor_filters = esp8266_exception_decoder

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
upload_port = COM4
upload_speed = 115200
build_type = debug
lib_deps =
  jfturcot/SimpleTimer
  links2004/WebSockets
  jandrassy/TelnetStream
  PaulStoffregen/OneWire@2.3.7
  git@github.com:Offbeat-IoT/ota.git
  gyverlibs/buildTime
  git@github.com:JustinOng/Arduino-LiquidCrystal-SWI2C-library.git
  git@github.com:felias-fogg/SlowSoftI2CMaster.git
  git@github.com:krzychb/EspSaveCrash.git
  git@github.com:bblanchon/ArduinoJson.git
  git@github.com:Lance-Uppercut/my_utils.git
  git@github.com:Lance-Uppercut/esp_utilities.git#main
  adafruit/DHT sensor library@^1.4.4
  milesburton/DallasTemperature@^3.11.0
  sparkfun/Sparkfun BMP180@^1.1.2
  LiquidCrystal_I2C@1.1.2
#  https://github.com/Densaugeo/base64_arduino #.3.0
  git@github.com:fcgdam/ESP8266-base64.git
[env:esp01_1m_ota]
extends = env:esp01_1m
build_type = release
upload_protocol = espota
upload_port = small-monitoring
board_build.ldscript = eagle.flash.1m64.ld
